Scott Berry - Assignment 2

Import Packages

In [22]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

Create layers for model according to specifications

In [23]:
inputs = keras.Input(shape=(5,))
hidden = layers.Dense(3, use_bias=True, activation='relu')
final = layers.Dense(1, use_bias=True, activation='sigmoid')

Create the model

In [24]:
x = hidden(inputs)
output = final(x)
model = keras.Model(inputs=inputs, outputs=output, name='Assignment_2')
print(model.summary())

Model: "Assignment_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 5)]               0         
                                                                 
 dense_6 (Dense)             (None, 3)                 18        
                                                                 
 dense_7 (Dense)             (None, 1)                 4         
                                                                 
Total params: 22
Trainable params: 22
Non-trainable params: 0
_________________________________________________________________
None


Create an arbitrary dataset

In [25]:
num_samples = 1000
target_output = 0.3
input_data = np.random.randn(num_samples, 5)
targets = np.full((num_samples, 1), target_output)

Compile and train model

In [26]:
model.compile(
    loss=keras.losses.MeanSquaredError(),
    optimizer=keras.optimizers.SGD(learning_rate=0.1),
    metrics=['accuracy']
)
model.fit(input_data, targets, batch_size=32, epochs=100)

Epoch 1/100
32/32 [==============================] - 0s 2ms/step - loss: 0.0634 - accuracy: 0.0000e+00
Epoch 2/100
32/32 [==============================] - 0s 2ms/step - loss: 0.0336 - accuracy: 0.0000e+00
Epoch 3/100
32/32 [==============================] - 0s 2ms/step - loss: 0.0210 - accuracy: 0.0000e+00
Epoch 4/100
32/32 [==============================] - 0s 2ms/step - loss: 0.0150 - accuracy: 0.0000e+00
Epoch 5/100
32/32 [==============================] - 0s 1ms/step - loss: 0.0118 - accuracy: 0.0000e+00
Epoch 6/100
32/32 [==============================] - 0s 1ms/step - loss: 0.0096 - accuracy: 0.0000e+00
Epoch 7/100
32/32 [==============================] - 0s 1ms/step - loss: 0.0080 - accuracy: 0.0000e+00
Epoch 8/100
32/32 [==============================] - 0s 1ms/step - loss: 0.0067 - accuracy: 0.0000e+00
Epoch 9/100
32/32 [==============================] - 0s 1000us/step - loss: 0.0057 - accuracy: 0.0000e+00
Epoch 10/100
32/32 [==============================] - 0s 1ms/step - lo

Test output

In [27]:
random_input = np.random.randn(1,5)
out = tf.squeeze(model.predict(random_input)).numpy()
print("Prediction: {:.2f}".format(out))

Prediction: 0.30


Print weights and biases

In [28]:
hl_weight, hl_bias, fl_weight, fl_bias = model.get_weights()[0:4]
print("Hidden Layer Weights:", hl_weight)
print("Hidden Layer Biases:", hl_bias)
print("Final Layer Weights", fl_weight)
print("Final Layer Biases:", fl_bias)

Hidden Layer Weights: [[ 0.62902826  0.2627437  -0.02776143]
 [-0.55061555  0.54273367  0.32308063]
 [ 0.05085528 -0.20063917 -0.6269278 ]
 [ 0.59940857  0.4006448   0.05345453]
 [ 0.62612396 -0.48861417  0.33413586]]
Hidden Layer Biases: [-0.09096894 -0.34770665  0.01044082]
Final Layer Weights [[-0.00035927]
 [ 0.00173503]
 [-0.00509202]]
Final Layer Biases: [-0.8456463]
