Scott Berry - Assignment 1

Part 1
1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [71]:
import tensorflow as tf

vector = tf.constant([10, 10])
print("Vector:", vector)
scalar = tf.constant(7)
print("Scalar:", scalar)
matrix = tf.constant([[10, 7],
                      [7, 10]])
print("Matrix:", matrix)
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
print("Tensor:", tensor)

Vector: tf.Tensor([10 10], shape=(2,), dtype=int32)
Scalar: tf.Tensor(7, shape=(), dtype=int32)
Matrix: tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
Tensor: tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


2. Find the shape, rank and size of the tensors you created in 1.

In [72]:
vector_shape = vector.shape
print("Vector Shape:", vector_shape)
vector_rank = vector.ndim
print("Vector Rank:", vector_rank)
vector_size = tf.size(vector).numpy()
print("Vector Size:", vector_size)
scalar_shape = scalar.shape
print("Scalar Shape:", scalar_shape)
scalar_rank = scalar.ndim
print("Scalar Rank:", scalar_rank)
scalar_size = tf.size(scalar).numpy()
print("Scalar Size:", scalar_size)
matrix_shape = matrix.shape
print("Matrix Shape:", matrix_shape)
matrix_rank = matrix.ndim
print("Matrix Rank:", matrix_rank)
matrix_size = tf.size(matrix).numpy()
print("Matrix Size:", matrix_size)
tensor_shape = tensor.shape
print("Tensor Shape:", tensor_shape)
tensor_rank = tensor.ndim
print("Tensor Rank:", tensor_rank)
tensor_size = tf.size(tensor).numpy()
print("Tensor Size:", tensor_size)

Vector Shape: (2,)
Vector Rank: 1
Vector Size: 2
Scalar Shape: ()
Scalar Rank: 0
Scalar Size: 1
Matrix Shape: (2, 2)
Matrix Rank: 2
Matrix Size: 4
Tensor Shape: (3, 2, 3)
Tensor Rank: 3
Tensor Size: 18


3. Create two tensors containing random values between 0 and 1 with shape [6, 550].

In [73]:
import numpy as np

random_1 = tf.constant(np.random.rand(6, 550))
print("Random 1:", random_1)
random_2 = tf.constant(np.random.rand(6, 550))
print("Random 2:", random_2)

Random 1: tf.Tensor(
[[0.55528205 0.02005244 0.71192678 ... 0.62929839 0.74904284 0.91576279]
 [0.35580415 0.9028332  0.0410888  ... 0.94471842 0.48513377 0.3890863 ]
 [0.58025638 0.38362562 0.97379972 ... 0.42985307 0.29750797 0.54282999]
 [0.97346894 0.44754232 0.73161148 ... 0.68386063 0.57625434 0.78221991]
 [0.21055195 0.22010494 0.84231394 ... 0.04618867 0.08673802 0.82117968]
 [0.78259472 0.50397235 0.3273401  ... 0.00283099 0.23743923 0.87507323]], shape=(6, 550), dtype=float64)
Random 2: tf.Tensor(
[[4.54587705e-01 3.25440900e-01 7.08750340e-01 ... 1.22404333e-01
  2.13642610e-01 8.93837829e-01]
 [1.30013982e-01 6.40197278e-01 5.22135556e-01 ... 8.53132914e-01
  2.83799105e-01 4.54301033e-01]
 [1.35340539e-04 6.86634227e-01 4.38543556e-01 ... 8.21709742e-01
  7.29886787e-01 8.00166205e-01]
 [8.88447524e-01 5.02753686e-01 3.87900592e-01 ... 7.25623267e-01
  3.96525887e-01 9.69424277e-01]
 [8.79485031e-01 2.90816660e-01 4.44225189e-02 ... 3.52636846e-01
  8.12424396e-01 6.587571

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [74]:
random_product = tf.matmul(tf.transpose(random_1), random_2)
print("Random Product:", random_product)

Random Product: tf.Tensor(
[[1.82877802 1.63205738 1.74403303 ... 2.1515962  1.24286935 2.84610673]
 [1.02682955 1.3137065  1.17420207 ... 1.82686279 0.92427359 1.67184393]
 [1.92066436 1.65423097 1.49316646 ... 1.96889749 1.86679197 2.47473367]
 ...
 [1.05888886 1.46299627 1.39701048 ... 1.75061738 1.0251469  2.00170358]
 [1.13749717 1.15684878 1.30080236 ... 1.35733948 0.82677085 1.9234513 ]
 [2.42081014 1.85884726 2.01526274 ... 2.33167803 1.72730846 3.06413487]], shape=(550, 550), dtype=float64)


5. Create a tensor with random values between 0 and 1 with shape [135, 135, 3].

In [75]:
random_3 = tf.constant(np.random.rand(135, 135, 3))
print("Random 3:", random_3)

Random 3: tf.Tensor(
[[[0.47977506 0.26940868 0.57741313]
  [0.77905657 0.45145245 0.15345235]
  [0.49985381 0.54293298 0.34868987]
  ...
  [0.78515256 0.69369346 0.97307623]
  [0.8320431  0.53868711 0.2533959 ]
  [0.10415774 0.24585193 0.35232682]]

 [[0.68309905 0.12406424 0.83360523]
  [0.11875478 0.93324902 0.17829727]
  [0.74052175 0.38916003 0.52633426]
  ...
  [0.56316767 0.54478693 0.67659214]
  [0.13613645 0.6484064  0.41223865]
  [0.95556966 0.78966687 0.93214451]]

 [[0.74248945 0.91936043 0.79224212]
  [0.57089758 0.26581214 0.74280169]
  [0.03775847 0.75191028 0.42419968]
  ...
  [0.42463484 0.29082059 0.87452908]
  [0.78381973 0.97884863 0.89567582]
  [0.9442577  0.98558015 0.53155216]]

 ...

 [[0.26192985 0.69871077 0.46900321]
  [0.8598647  0.73699751 0.19925491]
  [0.70057214 0.88720097 0.84759053]
  ...
  [0.6671156  0.4121906  0.89446564]
  [0.93770518 0.2412108  0.43096926]
  [0.98509728 0.73852111 0.42853967]]

 [[0.65454881 0.37824871 0.41235035]
  [0.12944978 0.

6. Find the min and max values of the tensor you created in 5.

In [76]:
random_min = tf.reduce_min(random_3)
print("Random Min:", random_min)
random_max = tf.reduce_max(random_3)
print("Random Max:", random_max)

Random Min: tf.Tensor(2.2799692888764156e-05, shape=(), dtype=float64)
Random Max: tf.Tensor(0.9999833783901702, shape=(), dtype=float64)


7. Created a tensor with random values of shape [1, 135, 135, 28] then squeeze it to change the shape to [135, 135, 28].

In [77]:
random_4 = tf.random.Generator.from_seed(42)
random_4 = random_4.normal(shape=(1, 135, 135, 28))
print("Random 4:", random_4)
random_4_squeezed = tf.squeeze(random_4)
print("Random 4 Squeezed:", random_4_squeezed)

Random 4: tf.Tensor(
[[[[-7.56580293e-01 -6.85470179e-02  7.59502575e-02 ... -5.24474740e-01
    -1.03453290e+00  1.30669010e+00]
   [-1.51845729e+00 -4.58521098e-01  5.71466327e-01 ...  2.67910528e+00
     1.09148061e+00  3.31496149e-01]
   [-6.79589152e-01  4.47236776e-01 -1.78115845e-01 ...  5.08094728e-02
     1.72120607e+00 -6.57512486e-01]
   ...
   [ 5.89750670e-02  7.70883441e-01 -1.90485513e+00 ... -1.07608676e-01
    -3.42550814e-01  9.89552081e-01]
   [-1.80061555e+00  3.57340217e-01  1.93566871e+00 ...  1.13655913e+00
    -4.56918061e-01  1.02984536e+00]
   [ 4.87509787e-01 -1.97188854e-01 -1.52990854e+00 ...  7.91458249e-01
    -4.80736762e-01 -9.96623933e-01]]

  [[-6.87561035e-02 -1.54220068e+00 -4.98402983e-01 ... -1.26698911e+00
     2.26338580e-03 -1.17119980e+00]
   [-3.25447656e-02 -8.13786328e-01 -2.02301621e-01 ... -1.11319587e-01
    -9.89492834e-01 -1.23322263e-01]
   [-1.94080842e+00  5.85251629e-01  2.45584026e-01 ...  9.68298018e-02
     1.59199917e+00  1.071

Part 2
1. Then for what closed-form solutions of w_0 and w_1, will the above equation be minimum?
If,
$$
h_w(x^i) = w_0 + w_1x^i
$$
and
$$
C = \sum^n_{i=1} \frac{1}{2n}(h_w(x^i) - y^i)^2
$$

Minimum exists when C = 0 which occurs when:
$$
h_w(x^i) = y^i
$$
and therefore
$$
y^i = w_0 + w_1x^i
$$

2. What are the problems you might encounter if you wanted to compute the second derivatives of the loss function with respect to weights? How would you fix them?